// https://material-ui.com/demos/expansion-panels/#controlled-accordion
import Typography from '@material-ui/core/Typography';
import React, { Fragment } from 'react';
import FaqItem from './FaqItem';

const FAQAccordion = () => {
  const faqs = [
    {
      title: 'What is the Steem Blockchain?',
      content: (
        <Fragment>
          <p>
            A blockchain is a public, immutable, decentralized and
            censorship-resistant way of storing data secured by cryptography.{' '}
            <q>
              Steem is a social blockchain that grows communities and makes
              immediate revenue streams possible for users by rewarding them for
              sharing content.
            </q>{' '}
            Visit{' '}
            <a
              href="https://steem.com/"
              rel="noopener noreferrer nofollow"
              target="_blank"
            >
              steem.com
            </a>{' '}
            for more information.
          </p>
        </Fragment>
      ),
    },
    {
      title: 'What are MILES tokens?',
      content:
        'MILES tokens are a planned cryptocurrency token operating on the Steem Blockchain with functionality similar to STEEM, but with a rewards pool exclusively for TravelFeed posts. On top of earning more curation rewards and giving an account more influence over the MILES rewards pool, staking MILES tokens will give users access to several Premium features and additional revenue streams on TravelFeed. We will release more information on MILES in Q3 2019. We plan on rewarding past, current and future TravelFeed users and delegators by airdropping MILES to them, but we believe in building our platform first and with it a MILES economy deeply integrated into the platform, instead of launching a worthless token without a use case now.',
    },
    {
      title: 'Where does the money come from?',
      content:
        'STEEM, and in the future the TravelFeed MILES tokens, are inflationary currencies with a yearly inflation of currently around 10%. A large part of the new STEEM tokens generated by inflation goes towards the rewards pool that is distributed among content creators and curators.',
    },
    {
      title: 'What are miles and what does the airplane button do?',
      content:
        'On TravelFeed, you can upvote posts and comments by pressing the button with the airplane taking off. We call that "giving miles". You can give up to 10 miles per post, equaling a 100% upvote on Steem. The more miles you give, the less powerful they are, but your "fuel tank" recharges by 100 miles every day. The more miles are given to a post, the more visibility it will get and the higher the reward that the author will get from the rewards pool. The rewards for a post are not only determined by the total amount of miles received, but also by the influence (currently determined by Steem Power held) of each curator — one mile by a powerful account like @travelfeed can be worth more than ten miles from a small account.',
    },
    {
      title: 'What is a curator?',
      content:
        'A curator is anyone voting on TravelFeed posts, including yourself. By giving miles to a post before it goes viral, you can earn curation rewards from the rewards pool, potentially higher than the value of your vote. A TravelFeed curator is part of our team and controls miles given by the account @travelfeed.',
    },
    {
      title: 'How can I get miles from @travelfeed?',
      content: (
        <Fragment>
          <p>
            We operate a team of professional curators. Every day, we read all
            posts submitted to TravelFeed. The five best posts are featured on
            the front page and receive 10 miles, other posts can receive up to 5
            miles.
          </p>
        </Fragment>
      ),
    },
    {
      title: 'What are the quality requirements for posts?',
      content: (
        <Fragment>
          <p>
            If you want to post your blogs on TravelFeed, please make sure that
            your post fits our criteria:
          </p>
          <ul>
            <li>Only original content;</li>
            <li>English (or bilingual);</li>
            <li>At least 250 words in English;</li>
            <li>
              Proper sourcing if you are using any media that are not your own;
            </li>
            <li>No copyright violations;</li>
            <li>Only travel-related content.</li>
          </ul>
        </Fragment>
      ),
    },
    {
      title: 'Can I participate in TravelFeed from other Steem frontends?',
      content:
        'As long as your post contains the tag #travelfeed and meets our criteria, it will be visible on TravelFeed and eligible for curation. However, we recommend using TravelFeed to author your posts to make use of our unique features, such as the location picker within the editor. In the future, there will be financial incentives for posting through TravelFeed.',
    },
    {
      title: 'Does TravelFeed charge beneficiary rewards?',
      content:
        "We don't take anything from your hard-earned rewards and will never set any beneficiaries without your consent.",
    },
  ];
  return (
    <Fragment>
      <div>
        {faqs.map(item => {
          return <FaqItem title={item.title} content={item.content} />;
        })}
      </div>
      <Typography gutterBottom variant="h5" className="pt-4">
        More Questions?
      </Typography>
      <p>
        We are happy to answer your questions and add them to the FAQ! You can
        contact us:
      </p>
      <ul>
        <li>
          By email:{' '}
          <a
            href="mailto:travelfeed.steemit@gmail.com"
            rel="noopener noreferrer nofollow"
            target="_blank"
          >
            travelfeed.steemit@gmail.com
          </a>
        </li>
        <li>
          By visiting our Discord:{' '}
          <a
            href="https://discord.gg/jWWu73H"
            rel="noopener noreferrer nofollow"
            target="_blank"
          >
            https://discord.gg/jWWu73H
          </a>
        </li>
      </ul>
    </Fragment>
  );
};

export default FAQAccordion;
